Repository fusionjs/fusion-apollo-universal-client, pull requests merged in 2018-11, with the labels that each got.

#164 Release v1.4.3
  package.json
Labels: release

#165 Update flow types for flow@0.85
  package.json
  src/__tests__/integration.node.js
  src/index.js
  yarn.lock
Labels: bugfix, dependencies, greenkeeping

#167 Create a new in memory cache per apollo client on the server
  src/index.js
Labels: bugfix

#168 Release v1.4.4
  package.json
Labels: release

#166 Update cache logic to create a new cache per request
  README.md
  docs/migrations/00166.md
  src/__tests__/exports.js
  src/__tests__/index.js
  src/index.js
Labels: breaking

#169 Release v2.0.0-0
  package.json
Labels: release

#170 Release v2.0.0
  package.json
Labels: release

#172 Fix flow types of plugin export
  package.json
  src/index.js
  yarn.lock
Labels: bugfix

#174 Release v2.0.1-0
  package.json
Labels: release

#173 Upgrade dependencies
  .npmrc
  package.json
Labels: greenkeeping

#176 Fix types for cache token
  src/index.js
Labels: bugfix
