Repository fusionjs/fusion-apollo-universal-client, pull requests merged in 2018-10, with the labels that each got.

#149 Upgrade dependency version
  package.json
  yarn.lock
Labels: greenkeeping

#152 Set ssrMode to true for both server and client
  src/index.js
Labels: bugfix

#160 Implement CI for multiple node versions
  .buildkite/pipeline.yml
  Dockerfile
  docker-compose.yml
Labels: refactor

#162 Add initial integration testing framework for apollo client
  app-fixture/.fusionrc.js
  app-fixture/.gitignore
  app-fixture/src/main.js
  app-fixture/src/pages/home.js
  app-fixture/src/root.js
  package.json
  src/__tests__/exports.js
  src/__tests__/index.js
  src/__tests__/integration.node.js
  yarn.lock
Labels: bugfix
