Repository fusionjs/fusion-apollo-universal-client, pull requests merged in 2018-09, with the labels that each got.

#134 Add ApolloClientCacheToken for specifying and utilizing a cache
  README.md
  src/__tests__/exports.js
  src/__tests__/index.js
  src/index.js
Labels: feature

#136 Update GetApolloClientLinksToken implementation for handling terminal links
  README.md
  package.json
  src/__tests__/exports.js
  src/__tests__/index.js
  src/index.js
  yarn.lock
Labels: feature

#137 Release v1.4.0-1
  package.json
Labels: release

#138 Update docs for GetApolloClientLinksToken
  README.md
Labels: docs

#139 Provide context for getApolloLinks
  src/index.js
Labels: feature

#142 Release v1.4.0
  package.json
Labels: release

#144 Set connectToDevTools for Apollo developer tools
  flow-typed/globals.js
  src/index.js
Labels: bugfix
