Repository fusionjs/fusion-apollo-universal-client, pull requests merged in 2018-08, with the labels that each got.

#128 Add ApolloClientLinkToken for composing with the default ApolloLink
  README.md
  package.json
  src/__tests__/exports.js
  src/__tests__/index.js
  src/index.js
  yarn.lock
Labels: feature

#129 Release v1.4.0-0
  package.json
Labels: release

#130 Disable ssrMode client side
  src/index.js
Labels: bugfix
