Repository fusionjs/fusion-apollo-universal-client, pull requests merged in 2019-03, with the labels that each got.

#197 Allow to specify local state resolvers
  README.md
  package.json
  src/__tests__/exports.js
  src/__tests__/local-state.js
  src/index.js
  yarn.lock
Labels: feature

#198 Release v2.2.0-0
  package.json
Labels: release

#199 Release v2.2.0
  package.json
Labels: release

#200 Update to reference `fusion-plugin-apollo`
  README.md
  app-fixture/src/main.js
  docs/migrations/00200.md
  flow-fixtures/index.js
  package.json
  src/__tests__/exports.js
  src/__tests__/index.js
  src/__tests__/local-state.js
  src/index.js
  yarn.lock
Labels: breaking

#202 Release v3.0.0-0
  package.json
Labels: release
