Repository fusionjs/fusion-apollo-universal-client, pull requests merged in 2019-01, with the labels that each got.

#186 Add default for graphql endpoint token
  src/index.js
Labels: feature

#187 Set default context to fusion ctx
  src/index.js
Labels: feature

#189 Update dependencies
  package.json
  src/index.js
  yarn.lock
Labels: bugfix

#190 Release v2.1.0-1
  package.json
Labels: release

#195 Release v2.1.0
  package.json
Labels: release
